import {PropsWithChildren} from 'react';
import type {Metadata} from 'next';

/* style */
import 'assets/styles/index.scss';

/* layouts */
import ThemeBody from 'components/mui/ThemeBody';
import RecoilProvider from 'components/layouts/RecoilProvider';
import StyledJsxRegistry from 'components/layouts/StyledJsxRegistry';

/* viewport */
export const viewport = 'width=device-width, initial-scale=1, maximum-scale=1';

export const metadata: Metadata = {
  title: 'React Wep application',
  description: 'Generated by create next app'
  // themeColor: "#3D51FE",
  // icons: "",
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content={viewport} />
      </head>
      <RecoilProvider>
        <body className="root-body">
          <StyledJsxRegistry>
            <ThemeBody>{children}</ThemeBody>
          </StyledJsxRegistry>
        </body>
      </RecoilProvider>
    </html>
  );
}
